#$ -S /bin/sh
#$ -N trinity
#$ -o ../logs/$JOB_NAME.$JOB_ID.out
#$ -e ../logs/$JOB_NAME.$JOB_ID.err
#$ -cwd
#$ -l h_vmem=28G
#$ -l h_rt=30:00:00
#$ -pe smp 8
#$ -V

# assemble RNA seq data using tophat/cufflinks

set -e
set -u

#export PATH=/home/vicker/programs/bowtie2-2.2.3:${PATH}
export PATH=/home/vicker/programs/samtools-1.1:${PATH}
export PATH=/home/vicker/programs/bowtie-1.1.1:${PATH}
export PATH=/home/vicker/programs/trinityrnaseq_r20140717:${PATH}
trinity='/home/vicker/programs/trinityrnaseq_r20140717/Trinity'

${trinity} --seqType fq --JM 30G --CPU 8 \
	--left /home/vicker/vesca_annotation/tophat_mildew_Y1DAI/unmapped_R1.fq --right /home/vicker/vesca_annotation/tophat_mildew_Y1DAI/unmapped_R2.fq --output /home/vicker/vesca_annotation/trinity_Y1DAI
