#$ -S /bin/sh
#$ -N combine
#$ -o ../logs/$JOB_NAME.$JOB_ID.out
#$ -e ../logs/$JOB_NAME.$JOB_ID.err
#$ -cwd
#$ -l h_vmem=2G
#$ -l h_rt=5:00:00

# combine multiple filtered samples into one

set -e
set -u

mkdir -p /home/vicker/vesca_annotation/tophat_mildew_Ycombined
cat /home/vicker/vesca_annotation/tophat_mildew_YC/unmapped_R1.fq /home/vicker/vesca_annotation/tophat_mildew_Y1DAI/unmapped_R1.fq /home/vicker/vesca_annotation/tophat_mildew_Y8DAI/unmapped_R1.fq > /home/vicker/vesca_annotation/tophat_mildew_Ycombined/unmapped_R1.fq
cat /home/vicker/vesca_annotation/tophat_mildew_YC/unmapped_R2.fq /home/vicker/vesca_annotation/tophat_mildew_Y1DAI/unmapped_R2.fq /home/vicker/vesca_annotation/tophat_mildew_Y8DAI/unmapped_R2.fq > /home/vicker/vesca_annotation/tophat_mildew_Ycombined/unmapped_R2.fq
